server:
  port : 8092

spring:
  application:
    name: Hotel-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: shirish

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: false