server:
  port: 8091

spring:
  profiles:
    active: dev
  application:
    name: User-Service
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root 
    password: shirish
  config:
    import: optional:configserver:http://localhost:8095

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serverUrl:
#      defaultZone: http://localhost:8761/eureka


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    preferIpAddress: false


#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect








